version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '${MYSQL_PORT}:3306'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    restart: always
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql
  
  adminer:
    image: adminer
    ports:
      - ${ADMINER_PORT}:8080

volumes:
  dados: